FROM node:10.15.2-alpine as builder

WORKDIR React-project

RUN ls -alrt

RUN pwd

RUN npm install

RUN pwd && ls -alrt

RUN npm run-script build

FROM nginx:latest

COPY --from=builder React-project/build/. /usr/share/nginx/html/
